name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fozztexx/defoogi:1.4.2

    steps:
      - uses: actions/checkout@v4

      - name: Build release files
        run: make release

      # Upload each .zip separately
      - name: Upload zips individually
        run: |
          for zip in dist/*.zip; do
            echo "Uploading $zip"
            # Each zip gets uploaded separately
            gh-actions-upload() {
              local file=$1
              name=$(basename "$file")
              echo "Uploading $name..."
              # Call upload-artifact action for this single file
              # Because we cannot loop 'uses', we spawn a subprocess via separate workflow run
              gh workflow run dummy-upload.yml --ref $GITHUB_REF
            }
            gh-actions-upload "$zip"
          done
