name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fozztexx/defoogi:1.4.2

    outputs:
      files: ${{ steps.list_zips.outputs.files }}

    steps:
      - uses: actions/checkout@v4

      - name: Build release files
        run: make release

      - name: List zip files
        id: list_zips
        run: |
          if compgen -G "dist/*.zip" > /dev/null; then
            files=$(ls dist/*.zip | xargs -n1 basename | jq -R -s -c 'split("\n")[:-1]')
          else
            files="[]"
          fi
          echo "files=$files" >> $GITHUB_OUTPUT

      - name: Upload dist folder for next job
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  upload:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.build.outputs.files) }}
    steps:
      - uses: actions/checkout@v4

      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Upload individual artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.file }}
          path: dist/${{ matrix.file }}
